# docker-compose.yml

version: "3.9"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src

  api:
    build: ./api
    container_name: api
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - api

volumes:
  postgres-data:
